spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3307/1mg?serverTimezone=GMT%2B7&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
      maxLifetime: 27000000
      leakDetectionThreshold: 60000
  jpa:
    properties:
      show-sql: false
      format_sql: true

  task:
    execution:
      pool:
        core-size: 32
        max-size: 12800
        queue-capacity: 12800
  config:
    activate:
      on-profile: local
redis:
  host: localhost
  port: 6379